### ISSUE TITLE
Flux V2 based  on GITHUB_TOKEN

### ISSUE THREAD

**Issue by ibuchh** [aws-samples/aws-cdk-eks-fluxv2-example#2]
Hello,

Can you provide a workaround using GITHUB_TOKEN instead of SSH Key for **_secretName: string;_**

Thanks.

**Comment by andskli** [comment]
Hi @ibuchh,

While Flux does support GitHub specifically, I opted for the more generic approach with SSH keys here so that it can be used with other git hosting platforms. At the time of my assessment, using the GitHub integration with Flux did not provide significant value over the generic approach, and hence I opted for the sake of this example, for the latter.

Please re-open and this issue if you feel that this is no longer the case and platform specific integrations should be considered.
